/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'page-title': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'section-title': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'card-title': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        body: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        small: ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        table: ['13px', { lineHeight: '1.45', fontWeight: '500' }],
      },
      spacing: {
        sidebar: '260px',
        topbar: '72px',
      },
      borderRadius: {
        card: '18px',
        input: '14px',
        pill: '9999px',
      },
      boxShadow: {
        card: '0 4px 24px rgba(0, 0, 0, 0.06)',
        sm: '0 2px 8px rgba(0, 0, 0, 0.04)',
        md: '0 4px 20px rgba(0, 0, 0, 0.06)',
        lg: '0 10px 30px rgba(0, 0, 0, 0.08)',
      },
      colors: {
        teal: {
          sidebar: '#2C97AD',
          dark: '#247A8C',
          main: '#2C97AD',
          light: '#5BB8CA',
          surface: '#E8F6F9',
          highlight: 'rgba(255, 255, 255, 0.18)',
          prescription: '#E3F4F8',
        },
        admin: {
          main: '#2C97AD',
          dark: '#247A8C',
          light: '#5BB8CA',
          surface: '#E8F6F9',
        },
        user: {
          sidebar: '#43A047',
          main: '#43A047',
          dark: '#2E7D32',
          light: '#66BB6A',
          surface: '#E8F5E9',
          highlight: 'rgba(255, 255, 255, 0.18)',
          prescription: '#E8F5E9',
        },
        patient: {
          sidebar: '#1E88E5',
          main: '#1E88E5',
          dark: '#1565C0',
          light: '#42A5F5',
          surface: '#E3F2FD',
          highlight: 'rgba(255, 255, 255, 0.18)',
          card: '#E8F4FD',
        },
        lab: {
          sidebar: '#7B1FA2',
          main: '#8E24AA',
          dark: '#6A1B9A',
          light: '#AB47BC',
          surface: '#F3E5F5',
          highlight: 'rgba(255, 255, 255, 0.18)',
          card: '#FCE4EC',
        },
        neutral: {
          bg: '#F4F7F6',
          border: '#E5E7EB',
          'card-border': '#EEF2F1',
          text: '#1F2937',
          muted: '#6B7280',
          light: '#9CA3AF',
          'table-head': '#F9FAFB',
          'table-hover': '#F3F4F6',
        },
        status: {
          success: '#86EFAC',
          warning: '#FDBA74',
          danger: '#EF4444',
          info: '#2C97AD',
          pending: '#FB923C',
        },
        dark: {
          bg: '#0F172A',
          card: '#1E293B',
          border: '#334155',
          text: '#F8FAFC',
          muted: '#94A3B8',
          sidebar: '#1a5f6d',
        },
        badge: {
          'pending-bg': '#FFEDD5',
          'pending-text': '#C2410C',
          'complete-bg': '#DCFCE7',
          'complete-text': '#166534',
          'cancelled-bg': '#FEE2E2',
          'cancelled-text': '#991B1B',
          'inprogress-bg': '#E0F2FE',
          'inprogress-text': '#0369A1',
          'scheduled-bg': '#EDE9FE',
          'scheduled-text': '#5B21B6',
        },
      },
      transitionDuration: {
        hover: '150ms',
        DEFAULT: '200ms',
      },
    },
  },
  plugins: [],
}
